# Generated by Django 3.2.16 on 2022-12-08 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carService', '0033_auto_20210331_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceExtraLabor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laborName', models.CharField(blank=True, max_length=100, null=True)),
                ('laborPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('laborTaxRate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carService.service')),
            ],
        ),
    ]
